---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: todoapp
  namespace: default
  labels:
    app: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: "ghcr.io/kalpanamamnani/my-web-app:latest"
        ports:
          - containerPort: 80
        volumeMounts:
          - name: html-volume
            mountPath: /usr/share/nginx/html
  volumes:
    - name: html-volume
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: todoapp
  type: NodePort
  ports:
  - name: http
    targetPort: 80
    port: 80
