---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: todoApp
  namespace: default
  labels:
    app: todoAapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoAapp
  template:
    metadata:
      labels:
        app: todoAapp
    spec:
      containers:
      - name: todoApp
        image: "ghcr.io/kalpanamamnani/my-web-app:latest"
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo_app
  namespace: default
spec:
  selector:
    app: todo_app
  type: NodePort
  ports:
  - name: http
    targetPort: 80
    port: 80
