---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: todoapp
  namespace: default
  labels:
    app: todoaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: "ghcr.io/kalpanamamnani/my-web-app:latest"
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todoapp
  namespace: default
spec:
  selector:
    app: todoapp
  type: NodePort
  ports:
  - name: http
    targetPort: 80
    port: 80
